# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  fr3_joint1: 0.0
  fr3_joint2: -0.785
  fr3_joint3: 0.0
  fr3_joint4: -2.356
  fr3_joint5: 0.0
  fr3_joint6: 1.571
  fr3_joint7: 0.785
