path_tolerance: 0.005
resample_dt: 0.02
min_angle_change: 0.001

default_workspace_bounds: 2.0
start_state_max_bounds_error: 0.01
start_state_max_dt: 0.1
jiggle_fraction: 0.01
max_sampling_attempts: 500

goal_orientation_tolerance: 0.1
goal_position_tolerance: 0.01
default_planning_pipeline: stomp
planning_time: 30.0