controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_position_example_controller:
      type: franka_example_controllers/JointPositionExampleController

    joint_velocity_example_controller:
      type: franka_example_controllers/JointVelocityExampleController

    joint_impedance_example_controller:
      type: franka_example_controllers/JointImpedanceExampleController

    fr3_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_position_example_controller:
  ros__parameters:
    gazebo: true

fr3_arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    gazebo: true
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    gains:
      fr3_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fr3_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
      fr3_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
      fr3_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }


joint_velocity_example_controller:
  ros__parameters:
    gazebo: true
  
joint_impedance_example_controller:
  ros__parameters:
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5