planning_pipelines: [stomp, ompl, chomp]
default_planning_pipeline: stomp

stomp:
  planning_plugins:
    - stomp_moveit/StompPlanner
  request_adapters:
    - default_planning_request_adapters/ResolveConstraintFrames
    - default_planning_request_adapters/ValidateWorkspaceBounds
    - default_planning_request_adapters/CheckStartStateBounds
    - default_planning_request_adapters/CheckStartStateCollision
  response_adapters:
    - default_planning_response_adapters/AddTimeOptimalParameterization
    - default_planning_response_adapters/ValidateSolution
    - default_planning_response_adapters/DisplayMotionPath

  stomp_moveit:
    num_timesteps: 60
    num_iterations: 40
    num_iterations_after_valid: 0
    num_rollouts: 30
    max_rollouts: 30
    exponentiated_cost_sensitivity: 0.8
    control_cost_weight: 0.1
    delta_t: 0.1

  default_workspace_bounds: 2.0
  start_state_max_bounds_error: 0.01
  start_state_max_dt: 0.1
  jiggle_fraction: 0.01
  max_sampling_attempts: 500

ompl:
  planning_plugins:
    - ompl_interface/OMPLPlanner
  request_adapters:
    - default_planning_request_adapters/ResolveConstraintFrames
    - default_planning_request_adapters/ValidateWorkspaceBounds
    - default_planning_request_adapters/CheckStartStateBounds
    - default_planning_request_adapters/CheckStartStateCollision
  response_adapters:
    - default_planning_response_adapters/AddTimeOptimalParameterization
    - default_planning_response_adapters/ValidateSolution
    - default_planning_response_adapters/DisplayMotionPath

  default_workspace_bounds: 2.0
  start_state_max_bounds_error: 0.01
  start_state_max_dt: 0.1
  jiggle_fraction: 0.01
  max_sampling_attempts: 500

chomp:
  planning_plugins:
    - chomp_interface/CHOMPPlanner
  enable_failure_recovery: true
  request_adapters:
    - default_planning_request_adapters/ResolveConstraintFrames
    - default_planning_request_adapters/ValidateWorkspaceBounds
    - default_planning_request_adapters/CheckStartStateBounds
    - default_planning_request_adapters/CheckStartStateCollision
  response_adapters:
    - default_planning_response_adapters/AddTimeOptimalParameterization
    - default_planning_response_adapters/ValidateSolution
    - default_planning_response_adapters/DisplayMotionPath

  ridge_factor: 0.01

  default_workspace_bounds: 2.0
  start_state_max_bounds_error: 0.01
  start_state_max_dt: 0.1
  jiggle_fraction: 0.01
  max_sampling_attempts: 500
