chomp:
  fr3_arm:
    planning_plugin: chomp_interface/CHOMPPlanner
    request_adapters: >
      default_planner_request_adapters/AddTimeParameterization
      default_planner_request_adapters/FixWorkspaceBounds
      default_planner_request_adapters/FixStartStateBounds
      default_planner_request_adapters/FixStartStateCollision
      default_planner_request_adapters/FixStartStatePathConstraints
    start_state_max_bounds_error: 0.1
    max_iterations: 100
    smoothness_cost: 1.0
    obstacle_cost: 1.0
    obstacle_distance: 0.001
    joint_update_method: gradient_descent

  fr3_arm_hand:
    planning_plugin: chomp_interface/CHOMPPlanner
    request_adapters: >
      default_planner_request_adapters/AddTimeParameterization
      default_planner_request_adapters/FixWorkspaceBounds
      default_planner_request_adapters/FixStartStateBounds
      default_planner_request_adapters/FixStartStateCollision
      default_planner_request_adapters/FixStartStatePathConstraints
    start_state_max_bounds_error: 0.1
    max_iterations: 100
    smoothness_cost: 1.0
    obstacle_cost: 1.0
    obstacle_distance: 0.001
    joint_update_method: gradient_descent
