# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  fr3_joint1:
    has_position_limits: true
    min_position: -2.7437
    max_position: 2.7437
    has_velocity_limits: true
    max_velocity: 2.62
    has_acceleration_limits: true
    max_acceleration: 10.0

  fr3_joint2:
    min_position: -1.7837
    max_position: 1.7837
    has_velocity_limits: true
    max_velocity: 2.62
    has_acceleration_limits: true
    max_acceleration: 10.0


  fr3_joint3:
    min_position: -2.9007
    max_position: 2.9007
    has_velocity_limits: true
    max_velocity: 2.62
    has_acceleration_limits: true
    max_acceleration: 10.0


  fr3_joint4:
    min_position: -3.0421
    max_position: -0.1518
    has_velocity_limits: true
    max_velocity: 2.62
    has_acceleration_limits: true
    max_acceleration: 100.0


  fr3_joint5:
    min_position: -2.8065
    max_position: 2.8065
    has_velocity_limits: true
    max_velocity: 5.26
    has_acceleration_limits: true
    max_acceleration: 10.0

  fr3_joint6:
    min_position: 0.5445
    max_position: 4.5169
    has_velocity_limits: true
    max_velocity: 4.18
    has_acceleration_limits: true
    max_acceleration: 10.0

  fr3_joint7:
    min_position: -3.0159
    max_position: 3.0159
    has_velocity_limits: true
    max_velocity: 5.26
    has_acceleration_limits: true
    max_acceleration: 10.0

  fr3_finger_joint1:
    min_position: -0.11
    max_position: 0.11
    has_velocity_limits: true
    max_velocity: 4.18
    has_acceleration_limits: true
    max_acceleration: 10.0

  fr3_finger_joint2:
    min_position: -0.11
    max_position: 0.11
    has_velocity_limits: true
    max_velocity: 4.18
    has_acceleration_limits: true
    max_acceleration: 10.0
