planner_configs:
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
    goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
    delay_collision_checking: 1  # Stop collision checking as soon as C-free parent found. default 1
    enforce_joint_model_state_space: true

default_planning_pipeline: RRTstarkConfigDefault
fr3_arm:
  default_planning_pipeline: RRTstarkConfigDefault
  planner_configs:
    - RRTstarkConfigDefault
fr3_arm_hand:
  planner_configs:
    - RRTstarkConfigDefault

# path_tolerance: 0.005
# resample_dt: 0.02
# min_angle_change: 0.001
# start_state_max_bounds_error: 0.01
# start_state_max_dt: 0.5
# jiggle_fraction: 0.01
# max_sampling_attempts: 500
# default_workspace_bounds: 2.0