planning_pipelines:
  pipeline_names: ["chomp", "stomp", "ompl"]

  default_planning_pipeline: ompl

  ompl:
    planning_plugin: ompl_interface/OMPLPlanner

  chomp:
    planning_plugin: chomp_interface/CHOMPPlanner
    planning_time_limit: 10.0
    max_iterations: 200
    max_iterations_after_collision_free: 5
    smoothness_cost_weight: 0.1
    obstacle_cost_weight: 1.0
    learning_rate: 0.01
    smoothness_cost_velocity: 0.0
    smoothness_cost_acceleration: 1.0
    smoothness_cost_jerk: 0.0
    ridge_factor: 0.0
    use_pseudo_inverse: false
    pseudo_inverse_ridge_factor: 1e-4
    joint_update_limit: 0.1
    collision_clearance: 0.002
    collision_threshold: 0.07
    use_stochastic_descent: true
    enable_failure_recovery: false
    max_recovery_attempts: 5

trajectory_execution:
  time_parameterization: 'iterative'
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.1
  allowed_start_tolerance: 0.01

  stomp:
    planning_plugin: stomp_interface/STOMPPlanner
    num_timesteps: 60
    num_iterations: 40
    num_iterations_after_valid: 0
    num_rollouts: 30
    max_rollouts: 30
    exponentiated_cost_sensitivity: 0.5
    control_cost_weight: 0.1
    delta_t: 0.1
    debug: true