objects:
  - object_0

object_0:
  object_id: 0
  geometry_file: "box.sdf"
  x: 0.2
  y: 0.2
  z: 0.2
  R: 0.0
  P: 0.0
  Y: 0.0
  primitive_type: BOX # or SPHERE, CYLINDER, CONE
  primitive_dims:
    x: 0.05
    y: 0.05
    z: 0.05