objects:
  - box
  - cylinder
  - sphere
  # - conic_flask
  # - round_bottomed_flask
  # - volumetric_flask

box:
  object_id: 0
  geometry_file: "box.sdf"
  x: 0.4
  y: -0.4
  z: 0.025
  R: 0.0
  P: 0.0
  Y: 0.0
  primitive_type: BOX # or SPHERE, CYLINDER, CONE
  primitive_dims:
    x: 0.05
    y: 0.05
    z: 0.05

cylinder:
  object_id: 1
  geometry_file: "cylinder.sdf"
  x: 0.4
  y: 0.0
  z: 0.05
  R: 0.0
  P: 0.0
  Y: 0.0
  primitive_type: CYLINDER # or SPHERE, CYLINDER, CONE
  primitive_dims:
    radius: 0.03
    height: 0.1

sphere:
  object_id: 2
  geometry_file: "sphere.sdf"
  x: 0.4
  y: 0.4
  z: 0.02
  primitive_type: SPHERE
  primitive_dims:
    radius: 0.03

conic_flask:
  object_id: 3
  geometry_file: "conic_flask.sdf"
  x: -0.4
  y: -0.4
  z: 0.5
  primitive_type: CONE
  primitive_dims:
    radius: 0.035
    height: 0.11

volumetric_flask:
  object_id: 4
  geometry_file: "volumetric_flask.sdf"
  x: -0.4
  y: 0.0
  z: 0.5
  primitive_type: CONE
  primitive_dims:
    radius: 0.055
    height: 0.24

round_bottomed_flask:
  object_id: 5
  geometry_file: "round_bottomed_flask.sdf"
  x: -0.4
  y: 0.4
  z: 0.5
  primitive_type: CONE
  primitive_dims:
    radius: 0.035
    height: 0.085