trajectory_execution:
  time_parameterization: "iterative"
  moveit_manage_controllers: true
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.1
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: true